# Generated by Django 5.0.2 on 2024-11-15 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HpPersonaldetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=50)),
                ('other_district', models.CharField(blank=True, max_length=50, null=True)),
                ('town', models.CharField(max_length=50)),
                ('other_town', models.CharField(blank=True, max_length=50, null=True)),
                ('outlet_name', models.CharField(max_length=100)),
                ('owner_name', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('pragati_app_enrolled', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Already Enrolled', 'Already Enrolled')], default='Not Specified', max_length=20)),
                ('existing_hpcl_customer', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Not Specified', max_length=10)),
                ('interested_in_futur_x', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Not Specified', max_length=10)),
                ('branding_flanges', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Not Specified', max_length=10)),
                ('branding_danglers', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Not Specified', max_length=10)),
                ('most_sold_lube', models.CharField(max_length=255)),
                ('application_of_lube', models.CharField(default='Not Specified', max_length=50)),
                ('retailer_id', models.PositiveIntegerField(default=0, unique=True)),
            ],
            options={
                'db_table': 'hp_personaldetails',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(default='Ahe', max_length=100)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('town', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProductDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('mco', 'Motorcycle Oil'), ('deo', 'Diesel Engine Oil'), ('pco', 'Passenger Car Oil')], max_length=20)),
                ('image', models.ImageField(upload_to='products/')),
                ('applications', models.TextField()),
                ('features', models.TextField()),
                ('quantities', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
