# Generated by Django 5.0.2 on 2024-11-15 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hppersonaldetails',
            name='interested_in_futur_x',
        ),
    ]
