# Generated by Django 5.0.2 on 2024-11-15 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hp', '0002_remove_hppersonaldetails_interested_in_futur_x'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('complete_shop', 'Complete Shop Photo'), ('dealer_board', 'Dealer Board Close shot'), ('inside_wall', 'Inside Wall'), ('flanges', 'Flanges'), ('dangler', 'Dangler'), ('interaction', 'Interaction'), ('others', 'Others')], default='others', max_length=50)),
                ('image', models.ImageField(upload_to='branding_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
