# Generated by Django 5.0.2 on 2024-11-19 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hp', '0006_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hppersonaldetails',
            name='interested_in_futur_x',
        ),
        migrations.AddField(
            model_name='order',
            name='delivery',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Not Specified', max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='interested_in_futur_x',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Not Specified', max_length=10),
        ),
    ]
