# Generated by Django 5.0.2 on 2024-11-20 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hp', '0007_remove_hppersonaldetails_interested_in_futur_x_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hppersonaldetails',
            name='delivery',
        ),
        migrations.RemoveField(
            model_name='order',
            name='retailer',
        ),
        migrations.AddField(
            model_name='brandingimage',
            name='retailer_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='retailer_id',
            field=models.CharField(default='00_100', max_length=10, unique=True),
        ),
        migrations.AddField(
            model_name='order',
            name='sku',
            field=models.CharField(default='1L', max_length=50),
        ),
        migrations.AlterField(
            model_name='hppersonaldetails',
            name='retailer_id',
            field=models.CharField(default='00_100', max_length=10, unique=True),
        ),
    ]
