# Generated by Django 5.0.2 on 2024-11-20 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hp', '0008_remove_hppersonaldetails_delivery_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandingimage',
            name='retailer_id',
            field=models.CharField(default='unknown', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='retailer_id',
            field=models.CharField(default='unknown', max_length=10),
        ),
    ]
