# Generated by Django 5.0.2 on 2024-11-20 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hp', '0009_alter_brandingimage_retailer_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hppersonaldetails',
            name='created_by',
            field=models.CharField(default='system', max_length=100),
        ),
        migrations.AddField(
            model_name='hppersonaldetails',
            name='created_date',
            field=models.CharField(default='2024-11-20 09:48:30', max_length=100),
        ),
        migrations.AddField(
            model_name='hppersonaldetails',
            name='sync_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.CharField(max_length=255),
        ),
    ]
