# Generated by Django 4.2.7 on 2026-02-13 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hp', '0010_hppersonaldetails_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hppersonaldetails',
            name='created_date',
            field=models.CharField(default='2026-02-13 08:17:25', max_length=100),
        ),
    ]
