# Generated by Django 5.0 on 2023-12-29 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='topics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.IntegerField()),
                ('topic_name', models.CharField(max_length=100)),
                ('youtube_link', models.URLField(max_length=500)),
            ],
        ),
    ]
