# Generated by Django 5.0 on 2023-12-29 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcmc_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topics',
            name='subject',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
