# Generated by Django 5.0 on 2023-12-29 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcmc_app', '0002_topics_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='topics_science',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('science_topic', models.CharField(max_length=100)),
                ('science_link', models.URLField(max_length=500)),
                ('subject', models.CharField(max_length=200)),
                ('section', models.IntegerField()),
            ],
        ),
    ]
