# Generated by Django 5.0.1 on 2024-01-03 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcmc_app', '0003_topics_science'),
    ]

    operations = [
        migrations.AddField(
            model_name='topics',
            name='img',
            field=models.ImageField(default='default_media\\Motion.png', upload_to='pics'),
        ),
        migrations.AddField(
            model_name='topics_science',
            name='img',
            field=models.ImageField(default='default_media\\Motion.png', upload_to='pics'),
        ),
    ]
