# Generated by Django 5.0 on 2024-01-07 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcmc_app', '0004_topics_img_topics_science_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='topics_maths',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.IntegerField()),
                ('maths_topic', models.CharField(max_length=100)),
                ('maths_link', models.URLField(max_length=500)),
                ('subject', models.CharField(max_length=200)),
                ('img', models.ImageField(default='default_media\\Motion.png', upload_to='pics')),
            ],
        ),
        migrations.DeleteModel(
            name='topics',
        ),
    ]
