# Generated by Django 5.0.1 on 2024-01-09 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcmc_app', '0005_topics_maths_delete_topics'),
    ]

    operations = [
        migrations.AddField(
            model_name='topics_maths',
            name='text_content',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topics_science',
            name='text_content',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
