# Generated by Django 4.2.7 on 2024-01-20 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcmc_app', '0006_topics_maths_text_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topics_maths',
            name='maths_link',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='topics_science',
            name='science_link',
            field=models.CharField(max_length=500),
        ),
    ]
