# Generated by Django 4.2.7 on 2024-02-22 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcmc_app', '0007_alter_topics_maths_maths_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='topics_maths',
            name='Topic_enable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='topics_science',
            name='Topic_enable',
            field=models.BooleanField(default=True),
        ),
    ]
