# Generated by Django 4.2.7 on 2024-02-23 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcmc_app', '0008_topics_maths_topic_enable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='topics_maths',
            name='Topic_order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topics_science',
            name='Topic_order',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
    ]
