# Generated by Django 4.2.7 on 2024-02-23 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcmc_app', '0009_topics_maths_topic_order_topics_science_topic_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=100)),
                ('school_id', models.IntegerField(unique=True)),
                ('school_logo', models.ImageField(upload_to='school_logos/')),
            ],
        ),
    ]
