# Generated by Django 5.0.2 on 2024-11-12 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcmc_app', '0011_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('two_wheeler', 'Two Wheeler'), ('four_wheeler', 'Four Wheeler')], max_length=20)),
                ('image', models.ImageField(upload_to='products/')),
                ('quantity_1l', models.IntegerField(default=0)),
                ('quantity_2l', models.IntegerField(default=0)),
                ('quantity_5l', models.IntegerField(default=0)),
                ('applications', models.TextField()),
                ('features', models.TextField()),
            ],
        ),
    ]
