# Generated by Django 5.0.2 on 2025-12-21 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcmc_app', '0013_standard_subject_topic_studymaterial_question_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
