# Generated by Django 5.0.2 on 2024-12-19 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_of_interest', models.CharField(max_length=255)),
                ('topic', models.CharField(max_length=255)),
                ('sample_work', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
